#!/bin/bash
# Install RainLoop webmail configuration on running server
set -e

RAINLOOP_DIR="/var/www/rainloop"

# Configure RainLoop application.ini
cat > "$RAINLOOP_DIR/data/_data_/_default_/configs/application.ini" << 'RLEOF'
; SysAdminHCP RainLoop Webmail Configuration

[webmail]
title = "SysAdminHCP Webmail"
loading_description = "SysAdminHCP"

[defaults]
language = "en"
theme = "Default"

[security]
allow_admin_panel = On
admin_panel_host = ""

[contacts]
enable = On

[logs]
enable = On
filename = "log.txt"

[debug]
enable = Off

[version]
current_version = "1.17.0"
RLEOF

# Create default domain config for local IMAP/SMTP (qmail/dovecot)
cat > "$RAINLOOP_DIR/data/_data_/_default_/domains/default.json" << 'DOMEOF'
{
  "imap": { "host": "localhost", "port": 143, "secure": false },
  "smtp": { "host": "localhost", "port": 25, "secure": false },
  "sieve": { "host": "localhost", "port": 4190, "secure": false }
}
DOMEOF

chown -R apache:apache "$RAINLOOP_DIR/data"

# Create Apache vhost for webmail
cat > /etc/httpd/conf.d/webmail.conf << 'WMEOF'
# SysAdminHCP Webmail (RainLoop)
# Auto-generated by installer — serves webmail.* for all domains

<VirtualHost *:80>
    ServerName webmail
    ServerAlias webmail.*

    DocumentRoot "/var/www/rainloop"
    <Directory "/var/www/rainloop">
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <FilesMatch \.php$>
        SetHandler "proxy:unix:/run/php-fpm/www.sock|fcgi://localhost"
    </FilesMatch>

    ErrorLog /var/log/httpd/webmail_error.log
    CustomLog /var/log/httpd/webmail_access.log combined
</VirtualHost>

<VirtualHost *:443>
    ServerName webmail
    ServerAlias webmail.*

    DocumentRoot "/var/www/rainloop"
    <Directory "/var/www/rainloop">
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    SSLEngine on
    SSLCertificateFile /etc/pki/tls/certs/localhost.crt
    SSLCertificateKeyFile /etc/pki/tls/private/localhost.key

    <FilesMatch \.php$>
        SetHandler "proxy:unix:/run/php-fpm/www.sock|fcgi://localhost"
    </FilesMatch>

    ErrorLog /var/log/httpd/webmail_ssl_error.log
    CustomLog /var/log/httpd/webmail_ssl_access.log combined
</VirtualHost>
WMEOF

# Create PHP-FPM pool for webmail
mkdir -p /var/lib/php/session/webmail
chown -R apache:apache /var/lib/php/session/webmail
chmod 1733 /var/lib/php/session/webmail

cat > /etc/php-fpm.d/webmail.conf << 'FPMEOF'
; SysAdminHCP Webmail PHP-FPM Pool
[webmail]
user = apache
group = apache

listen = /run/php-fpm/www.sock
listen.owner = apache
listen.group = apache
listen.mode = 0660

pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 5
pm.max_requests = 500

php_admin_value[error_log] = /var/log/php-fpm/webmail-error.log
php_admin_flag[log_errors] = on

php_value[session.save_handler] = files
php_value[session.save_path] = /var/lib/php/session/webmail

; Security
php_admin_value[open_basedir] = /var/www/rainloop:/tmp:/var/log/php-fpm:/var/lib/php/session
php_admin_value[disable_functions] = exec,passthru,shell_exec,system
FPMEOF

# Restart services
systemctl restart php-fpm 2>/dev/null || systemctl restart php8.2-php-fpm 2>/dev/null || true
systemctl restart httpd 2>/dev/null || true

echo "RainLoop webmail configured successfully!"